#!/bin/bash

export TESTE=samuel
echo ${TESTE}
echo $TESTE


echo 'TRAVIS_BRANCH = ' ${TRAVIS_BRANCH}
echo 'TRAVIS_PULL_REQUEST = ' ${TRAVIS_PULL_REQUEST}
echo 'TRAVIS_PULL_REQUEST_BRANCH = ' ${TRAVIS_PULL_REQUEST_BRANCH}
echo 'TRAVIS_TAG = ' ${TRAVIS_TAG}
echo 'TRAVIS_BUILD_ID' ${TRAVIS_BUILD_ID}
echo 'TRAVIS_BUILD_NUMBER = ' ${TRAVIS_BUILD_NUMBER}
